import React from 'react';

// TODO: AI Sprint - Implement full Welcome page functionality
// This is a functional stub to make the app runnable

interface WelcomeProps {
  // Add props as needed in future sprints
}

const Welcome: React.FC<WelcomeProps> = () => {
  return (
    <div style={{
      padding: '2rem',
      textAlign: 'center',
      background: 'linear-gradient(135deg, #1a1a2e 0%, #16213e 100%)',
      minHeight: '80vh',
      color: '#e6e6e6'
    }}>
      <h1 style={{ 
        fontSize: '3rem',
        marginBottom: '1rem',
        color: '#f72585'
      }}>
        🏰 Welcome to DungeonForge Online
      </h1>
      <p style={{ fontSize: '1.2rem', marginBottom: '2rem' }}>
        Your ultimate D&D companion for epic adventures!
      </p>
      <div style={{ display: 'flex', gap: '1rem', justifyContent: 'center', flexWrap: 'wrap' }}>
        <button style={{
          padding: '1rem 2rem',
          background: '#3a0ca3',
          color: 'white',
          border: 'none',
          borderRadius: '8px',
          cursor: 'pointer',
          fontSize: '1rem'
        }}>
          🎲 Roll Dice
        </button>
        <button style={{
          padding: '1rem 2rem',
          background: '#7209b7',
          color: 'white',
          border: 'none',
          borderRadius: '8px',
          cursor: 'pointer',
          fontSize: '1rem'
        }}>
          🧙‍♂️ Create Character
        </button>
        <button style={{
          padding: '1rem 2rem',
          background: '#f72585',
          color: 'white',
          border: 'none',
          borderRadius: '8px',
          cursor: 'pointer',
          fontSize: '1rem'
        }}>
          🗺️ Browse Campaigns
        </button>
      </div>
      <div style={{ marginTop: '3rem', fontSize: '0.9rem', opacity: 0.7 }}>
        <p>🤖 Generated by AI Agents | Ready for your next adventure!</p>
      </div>
    </div>
  );
};

export default Welcome;
